### ISSUE TITLE
ERROR: [youtube]

### ISSUE THREAD

**Issue by Yorksik** [Daenges/Spotify-Downloader-Bash#2]
Hi. Can you please tell me what the problem is? I want to download tracks from the list, but the following error pops up.

[scrin](https://ibb.co/KrVvBmm)

`./Downloader.sh liked.csv
Using 'yt-dlp' as downloader.
Found: 4 entries
Status: #1 downloads started - 25%
Status: #2 downloads started - 50%
Status: #3 downloads started - 75%
Status: #4 downloads started - 100%
All downloads have been started. Waiting for completion.
ERROR: [youtube] Q0oIoR9mLwc: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [youtube] dqVZaN4lnwQ: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [youtube] Wv2rLZmbPMA: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
ERROR: [youtube] qN4ooNx77u0: Unable to extract uploader id; please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U
/tmp/Dark Necessities.mp3: No such file or directory
/tmp/Never Go Away.mp3: No such file or directory
Finished: Dark Necessities
Finished: Never Go Away
/tmp/Dive.mp3: No such file or directory
Finished: Dive
/tmp/Sign of the Times.mp3: No such file or directory
Finished: Sign of the Times
`

**Comment by Daenges** [comment]
Most likely an old version of yt-dlp. Do `yt-dlp -v` and compare it to [their releases](https://github.com/yt-dlp/yt-dlp/releases). To get a recent version install it with `pip`.

**Comment by Yorksik** [comment]
Thanks
